idf_component_register(
    SRCS
        "main.c"
        "wifi.c"
        "sensors.c"
        "http_post.c"
        "led.c"
        "nvs_cfg.c"
        "offline_buffer.c"
        "ota.c"
        "provisioning.c"
    INCLUDE_DIRS "."
    REQUIRES
        nvs_flash
        esp_wifi
        esp_event
        esp_http_client
        esp_http_server
        esp_https_ota
        app_update
        esp_netif
        spiffs
        esp_timer
        esp_adc
        lwip
        driver
        json
        esp-tls
        mbedtls
)
